### ISSUE TITLE
GCI: Structure Proposal for Moving the Project to a Library

### ISSUE THREAD

**Issue by HITGIF** [jboss-outreach/compressor-head-android#111]
This project should be convert to a library with a sample app connected to it.
#### APPROACH
- **MOVE** (Refactor) the following files in `app` module:
[`CompressorHead.java`](https://github.com/jboss-outreach/compressor-head-android/blob/master/app/src/main/java/com/community/jboss/compressorhead/utils/CompressorHead.java)  (which contains the APIs)  and [`Constants.java`](https://github.com/jboss-outreach/compressor-head-android/blob/master/app/src/main/java/com/community/jboss/compressorhead/utils/Constants.java) (which contains the constant values)
**INTO** the existing [`CompressorHead module`](https://github.com/jboss-outreach/compressor-head-android/tree/master/compressor_head/src/main/java/com/community/jboss/compressorhead).

- Add [Retrofit](http://square.github.io/retrofit/) to the library for constructing and sending HTTP request.

- Add [Picasso](http://square.github.io/picasso/) to the library for image downloading.

-  (Optional) Change the `app` module name into `sample`.

**Comment by garg-anuj** [comment]
@HITGIF Will we not need to create one extra module?

**Comment by HITGIF** [comment]
No, as a CompressorHead module is already existing.

**Comment by m-murad** [comment]
Why would you use `Retrofit`? Retrofit should not be used for downloading images. Suggest some other library for image download.

**Comment by HITGIF** [comment]
@m-murad Well... as said in the task description, "Library will be using rest api with Retrofit". 
For image downloading, I will suggest to use Picasso :)

**Comment by HITGIF** [comment]
Have editted my proposal
