### ISSUE TITLE
Translation of Project to Hindi.

### ISSUE THREAD

**Issue by jatinluthra14** [jboss-outreach/compressor-head-android#66]
Here is the PR:
https://github.com/jboss-outreach/compressor-head-android/pull/65

**Comment by jatinluthra14** [comment]
![screenshot_1512360536](https://user-images.githubusercontent.com/10234506/33535979-240d8bae-d8d7-11e7-8601-f7a7da52eab4.png)

**Comment by divyanshkul** [comment]
I can work on translating the readme file to hindi. What say? @jatinluthra14

**Comment by jatinluthra14** [comment]
Is it required?  If mentor ensures then surely you can. I'll help if needed

**Comment by m-murad** [comment]
@divyanshkul 
hindi translation has already been done.
Do some other translation.

**Comment by divyanshkul** [comment]
Okay! @m-murad

**Comment by jatinluthra14** [comment]
@m-murad
He is asking for Readme

**Comment by divyanshkul** [comment]
@m-murad yeah, talking about the readme file.

**Comment by divyanshkul** [comment]
@m-murad can I ?

**Comment by zwliew** [comment]
Could you close this issue, now that #106 is merged?
