### ISSUE TITLE
Fixing image proportion while scaling

### ISSUE THREAD

**Issue by SachinRammoorthy** [jboss-outreach/compressor-head-android#77]
Currently in the compressor-head android app, there are EditTexts to set the height and width required. However, a user will not be able to set the height and width without knowing the proportion of the image. 

Further, the user must be aware of the dimensions of the image in order to set a feasible value for both the height and width.

I propose the following feature additions to the compressor-head android app:
- a checkbox for "Conserve proportions" (when selected, when either height or width is typed 
  in, the other should automatically scale),
- a feature in which the original height and width of the image is displayed once the url is inputted,

With this addition, the user will be able to compress images with more flexibility regarding preserving the proportions of the image.

I am interested in this feature because I face trouble every time I try to scale an image up or down. It ends up resizing unevenly. This is a pestering problem that needs to be solved!

To add this feature:
- Add a checkbox and 2 textviews in the xml layout
- If the checkbox is checked, get the original dimensions of the image and store in variables.
- set text of textviews to originalHeight and originalWidth
- When EditText _heightET_ is inputted, setText of _widthET_ to (_heightET_ * (originalHeight/originalWidth))

I hope this new feature is useful!

![screen shot 2017-12-05 at 9 44 11 pm](https://user-images.githubusercontent.com/20569603/33617356-77fabf1e-da05-11e7-9c2e-827ef468aace.png)

**Comment by zwliew** [comment]
This issue can be closed now that #99 is merged.
