### ISSUE TITLE
Image Preview to avoid entering wrong url

### ISSUE THREAD

**Issue by SachinRammoorthy** [jboss-outreach/compressor-head-android#79]
Currently in the app, there is no way to tell if the url inputted by the user is correct or not.

Thus, I propose to add a feature where a small image preview of the url is available.

With this addition, you will no longer have to double check that the url is right, and you can also view if the new proportions you are setting are correct.

I am interested in this feature because I have plenty of experience in pasting incorrect urls, and in setting incorrect and scaling images unevenly.

To add this feature, we can use Picasso.
`Picasso.with(context).load(ImageURL).resize(width,height).into(imageView);`

Hope it helps as an addition!

![screen shot 2017-12-05 at 9 54 28 pm](https://user-images.githubusercontent.com/20569603/33617865-ecd07f58-da06-11e7-9b78-80918ab55778.png)

**Comment by zwliew** [comment]
This task can be closed now that #99 is merged.
